#!/bin/sh
#

# Creates ethX interfaces on G2 firewalls with integrated switchs
/usr/Firewall/sbin/switchd -i
ret=$?
if [ $ret != 0 ]; then
        echo "Switchd initialisation failed with code $ret"
fi
